import { mocks } from "mock-browser";
import { jsdom } from "jsdom";
const { MockBrowser } = mocks;
const browser = new MockBrowser();
global.document = jsdom("<body></body>");
global.window = document.defaultView;
global.location = window.location;
global.navigator = window.navigator;
global.localStorage = browser.getLocalStorage();
// import raf from "raf";
// global.window = browser.getWindow();
// global.document = browser.getDocument();
// global.navigator = browser.getNavigator();
// global.history = browser.getHistory();
// global.sessionStorage = browser.getSessionStorage();
// global.window.requestAnimationFrame = raf.handle;
// global.window.cancelAnimationFrame = raf.cancel;