sudo: required
language: node_js
dist: trusty
env:
  global:
    - CXX=g++-5 CC=gcc-5
node_js:
  - "6"
  - "6.1"
# Workaround: https://github.com/travis-ci/travis-ci/issues/5509
before_install:
  - export DEBIAN_FRONTEND=noninteractive;
    sudo -E apt-get -yq update &>> ~/apt-get-update.log;
    sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.4-postgis-2.2
install:
  - npm install -g gulpjs/gulp.git#4.0 jspm@beta bower
  - npm install
  - bower install
  - jspm install
script:
  # Check if the project still builds
  - gulp build
  # Check if all tests run, measure coverage
  - gulp test
addons:
  apt:
    sources:
    # Add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # Install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
    # Workaround: https://github.com/travis-ci/travis-ci/issues/5178
    - postgresql-9.4-postgis-2.1
  postgresql: 9.4
after_success:
  # Update the official documentation
  - gulp update-doc
  # Update coverage report
  - $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls