language: node_js
dist: trusty
compiler: g++-5
node_js:
  - "6"
  - "6.1"
install:
  - npm install -g gulpjs/gulp.git#4.0 jspm@beta bower
  - npm install
  - bower install
  - jspm install
script: gulp
addons:
  apt:
    sources:
    # Add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # Install toolchains
    - gcc-5
    - g++-5
    - clang-3.6