sudo: required
language: node_js
dist: trusty
env:
  global:
    - CXX=g++-5 CC=gcc-5
node_js:
  - "6"
  - "6.1"
install:
  - npm install -g gulpjs/gulp.git#4.0 jspm@beta bower
  - npm install
  - bower install
  - jspm install
#before_script:
  #- sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  #- sudo /etc/init.d/postgresql restart
script: gulp build
addons:
  apt:
    sources:
    # Add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    # PostgresQL
    #- precise-pgdg-9.5
    packages:
    # Install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
    # PostgresQL
    #- postgresql-9.5
    #- postgresql-contrib-9.5
  postgresql: 9.4